# Generated by Django 3.2.4 on 2021-07-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPlate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previous_records',
            name='user',
            field=models.IntegerField(max_length=10),
        ),
    ]
