# Generated by Django 3.2.4 on 2021-07-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPlate_app', '0002_alter_previous_records_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previous_records',
            name='user',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
