# Generated by Django 3.2.4 on 2021-07-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPlate_app', '0006_alter_previous_records_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previous_records',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
